name: 
  C:\Users\timch\Documents\University\AI-n-Machine-Learning-2\RPS-Hand-Gesture-Recognition\.conda
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.3.1=pyhd8ed1ab_0
  - anyio=4.12.0=pyhcf101f3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py311h3485c13_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_3
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyhcf101f3_1
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - blas=1.0=mkl
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - bottleneck=1.4.2=py311h540bb41_1
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotli-python=1.2.0=py311hc5da9e4_1
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h2466b09_0
  - ca-certificates=2025.12.2=haa95532_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=h91e5215_2
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py311h3485c13_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py311h3fd045d_3
  - cycler=0.12.1=pyhcf101f3_2
  - debugpy=1.8.17=py311h5dfdfe8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - eigen=3.4.0=h477610d_1
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h9214b88_0
  - filelock=3.20.0=pyhd8ed1ab_0
  - flatbuffers=24.3.25=h63175ca_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.0=py311h3f79411_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=h57928b3_0
  - fribidi=1.0.16=hfd05255_0
  - gast=0.7.0=pyhd8ed1ab_0
  - gdown=5.2.0=pyhd8ed1ab_1
  - gettext=0.22.5=h5728263_3
  - gettext-tools=0.22.5=h5a7288d_3
  - giflib=5.2.2=h64bf75a_0
  - glib=2.84.0=h3d4babf_0
  - glib-tools=2.84.0=h4394cf3_0
  - google-pasta=0.2.0=pyhd8ed1ab_2
  - graphite2=1.3.14=hac47afa_2
  - grpcio=1.71.0=py311h05171df_0
  - gst-plugins-base=1.22.9=h001b923_1
  - gstreamer=1.22.9=hb4038d2_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.15.1=py311he283ef2_0
  - harfbuzz=10.2.0=he2f9f60_1
  - hdf5=1.14.5=ha36df97_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.2=h63175ca_0
  - idna=3.11=pyhd8ed1ab_0
  - impi_rt=2021.17.0=h57928b3_373
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.8.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - jpeg=9e=h8ffe710_2
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py311h1ea47a8_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.5.0=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - keras=3.12.0=pyh753f3f9_0
  - kiwisolver=1.4.9=py311h275cad7_2
  - krb5=1.21.3=hdf4eb48_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.15=ha5c8aab_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250127.0=cxx17_h4eb7d71_0
  - libasprintf=0.22.5=h5728263_3
  - libasprintf-devel=0.22.5=h5728263_3
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libclang13=14.0.6=default_h77d9078_1
  - libcurl=8.17.0=h43ecb02_0
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_15
  - libgettextpo=0.22.5=h5728263_3
  - libgettextpo-devel=0.22.5=h5728263_3
  - libglib=2.84.0=h7025463_0
  - libgomp=15.2.0=h8ee18e1_15
  - libgrpc=1.71.0=h35301be_0
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=2.1.4=hcfcfb64_0
  - libkrb5=1.21.3=h885b0b7_4
  - libogg=1.3.5=h2466b09_1
  - libpng=1.6.51=h7351971_0
  - libpq=17.6=h652a1e2_0
  - libprotobuf=5.29.3=he9d8c4a_0
  - libre2-11=2024.07.02=hd248061_3
  - libsodium=1.0.20=hc70643c_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.5.1=h44ae7cf_1
  - libvorbis=1.3.7=h5112557_2
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.13=0
  - libxml2=2.13.9=h741aa76_0
  - libxslt=1.1.43=h25c3957_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.7=h4fa8253_0
  - markdown=3.10=pyhcf101f3_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py311h3f79411_0
  - matplotlib=3.10.8=py311h1ea47a8_0
  - matplotlib-base=3.10.8=py311h1675fdf_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - minizip=4.0.6=hb638d1e_0
  - mistune=3.1.4=pyhcf101f3_0
  - mkl=2025.3.0=hac47afa_454
  - mkl-service=2.5.2=py311h0b37514_0
  - mkl_fft=2.1.1=py311h300f80d_0
  - mkl_random=1.3.0=py311ha5e6156_0
  - ml_dtypes=0.5.4=np2py311hf2e69b3_0
  - mpi=1.0=impi
  - mpi4py=4.1.1=py311h58c7454_102
  - munkres=1.1.4=pyhd8ed1ab_1
  - namex=0.1.0=pyhd8ed1ab_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numexpr=2.14.1=py311h7660c64_0
  - opencv=4.10.0=py311h545ae1a_4
  - openjpeg=2.5.0=ha2aaf27_2
  - openssl=3.6.0=h725018a_0
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - optree=0.18.0=py311h3fd045d_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311h42c1672_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.44=h99c9b8b_2
  - pillow=9.4.0=py311h76d9071_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py311hf893f09_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyside6=6.7.2=py311h2e8c42f_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.11.14=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-flatbuffers=24.3.25=pyhe33e51e_1
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py311hefeebc8_1
  - pywinpty=2.0.15=py311hda3d55a_1
  - pyyaml=6.0.3=py311h3f79411_0
  - pyzmq=27.1.0=py311hb77b9c8_0
  - qhull=2020.2=hc790b64_5
  - qtbase=6.7.3=hd088775_4
  - qtdeclarative=6.7.3=h885b0b7_1
  - qtshadertools=6.7.3=h885b0b7_1
  - qtsvg=6.7.3=h9d4b640_1
  - qttools=6.7.3=hcb596f7_1
  - qtwebchannel=6.7.3=h885b0b7_1
  - qtwebengine=6.7.2=h601c93c_0
  - qtwebsockets=6.7.3=h885b0b7_1
  - re2=2024.07.02=haf4117d_3
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rich=14.2.0=pyhcf101f3_0
  - rpds-py=0.30.0=py311hf51aa87_0
  - scikit-learn=1.7.2=py311h8a15ebc_0
  - scipy=1.16.3=py311hbd6d557_0
  - seaborn=0.13.2=py311haa95532_3
  - send2trash=1.8.3=pyh5737063_1
  - setuptools=80.9.0=py311haa95532_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8=pyhd8ed1ab_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2022.3.0=hd094cb3_1
  - tensorboard=2.19.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py311h1ea47a8_3
  - tensorflow=2.19.1=cpu_py311h6605a60_0
  - tensorflow-base=2.19.1=cpu_py311h4cf5749_0
  - termcolor=3.2.0=pyhd8ed1ab_0
  - terminado=0.18.1=pyh5737063_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.5.1=pyhcf101f3_0
  - tk=8.6.15=hf199647_0
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.2=py311h3485c13_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=17.0.0=py311h3485c13_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - werkzeug=3.1.4=pyhcf101f3_0
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - wrapt=2.0.1=py311h3485c13_1
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=h6a83c73_3
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h02ab6af_0
  - zstandard=0.25.0=py311hf893f09_1
  - zstd=1.5.7=h534d264_6
  - pip:
      - deprecated==1.3.1
      - imageio==2.37.2
      - jax==0.7.1
      - jaxlib==0.7.1
      - mediapipe==0.10.21
      - numpy==1.26.4
      - opencv-contrib-python==4.11.0.86
      - protobuf==4.25.8
      - sentencepiece==0.2.1
      - sounddevice==0.5.3
      - tf-keras-vis==0.8.7
prefix: 
  C:\Users\timch\Documents\University\AI-n-Machine-Learning-2\RPS-Hand-Gesture-Recognition\.conda
